apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hello-task
spec:
  steps:
    - name: echo
      image: ubuntu:18.04
      command:
        - echo
      args:
        - "osgnjh101"
    - name: echo
      image: ubuntu:18.04
      command:
        - echo
      args:
        - "osgnjh108"
        
